apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: garvit-test
  name: garvit-test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: garvit-test
  template:
    metadata:
      labels:
        app: garvit-test
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd
  strategy:
    type: Recreate

