apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: garvit-test
  name: garvit-test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: garvit-test
  template:
    metadata:
      labels:
        app: garvit-test
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd
          command: ["/bin/bash", "-c"] # override the default command
          args: ["sleep 5; exit 1"] # sleep for 30 seconds and then exit with an error
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

